# Generated by Django 6.0.2 on 2026-07-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('faculty', 'Faculty'), ('department', 'Department'), ('urgent', 'Urgent')], default='general', max_length=15)),
                ('audience', models.CharField(choices=[('all', 'All Students'), ('faculty', 'By Faculty'), ('department', 'By Department')], default='all', max_length=15)),
                ('target_faculty', models.CharField(blank=True, default='', max_length=150)),
                ('target_department', models.CharField(blank=True, default='', max_length=150)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
